kind: NetworkPolicy
apiVersion: net.alpha.kubernetes.io/v1alpha1
metadata:
  namespace: stars
  name: backend-policy
spec:
  podSelector:
    role: backend
  ingress:
    - from:
        - pods:
            role: frontend
      ports:
        - protocol: TCP
          port: 6379
