kind: NetworkPolicy
apiVersion: net.alpha.kubernetes.io/v1alpha1
metadata:
  namespace: stars
  name: frontend-policy
spec:
  podSelector:
    role: frontend 
  ingress:
    - from:
        - namespaces:
            role: client
      ports:
        - protocol: TCP
          port: 80
